### ISSUE TITLE
Problem with pv.py and Fronius in Solaranzeige

### ISSUE THREAD

**Issue by thedoctor586** [Deepintheeast/AWTRIX3-Connector#1]
Hej

I'm bit lost regarding config for pv.py

App: pv
 {'pv_Leistung': 0.53885772824287, 'pv_Akkustand_SOC': 88.9, 'pv_Wh_Heute': 20019.0}
Traceback (most recent call last):
  File "/home/pi/scripts/AWTRIX3-Connector/./awtrix3connect.py", line 166, in <module>
    main()
  File "/home/pi/scripts/AWTRIX3-Connector/./awtrix3connect.py", line 152, in main
    auswertung(app, data, config)
  File "/home/pi/scripts/AWTRIX3-Connector/auswertung.py", line 28, in auswertung
    module.auswertung(app, data, config)
  File "/home/pi/scripts/AWTRIX3-Connector/Auswertungen/pv.py", line 21, in auswertung
    {"t": str(int(data["pv_SOC"])) + " %", "c": "#00ff00"},
                  ~~~~^^^^^^^^^^
KeyError: 'pv_SOC'

it seems to fetch values for Leistung, Akkustand and Wh_Heute but giving error and stops.

**Comment by thedoctor586** [comment]
own fault wrong config

**Comment by Deepintheeast** [comment]
{'pv_Leistung': 0.53885772824287, 'pv_Akkustand_SOC': 88.9, 'pv_Wh_Heute': 20019.0}

you must use:

```
pv_Leistung     
pv_Akkustand_SOC    
pv_Wh_Heute
```
("pv_" is the Name off the "App")

```
""" Auswertung PV-Daten und Anzeige Leistung, Tagesertrag und SOC"""

# Importieren der benötigten Funktionen aus der Funktionen-Bibliothek
from funktionen import (
    awtrix3_send_app,
)

def auswertung(app, data, config):
    """ Auswertung PV-Daten und Anzeige Leistung, Tagesertrag und SOC"""

    data_app = {
        "text": [
            {"t": " PV: ", "c": "#fcff33"},
            {"t": str(int(data["pv_Leistung"])) + " W", "c": "#00ff00"},
            {"t": " + ", "c": "#ed7d3b"},
            {"t": "Tag: ", "c": "#fcff33"},
            {"t": str(round(float(data["pv_Wh_GesamtHeute"] / 1000), 2)) + " kWh",
                "c": "#00ff00"},
            {"t": " + ", "c": "#ed7d3b"},
            {"t": "SOC ", "c": "#fcff33"},
            {"t": str(int(data["pv_Akkustand_SOC"])) + " %", "c": "#00ff00"},
        ],
        "icon": 27283,
        "pushIcon": 2,
        "progress": int(data["pv_Akkustand_SOC"]),
        "progressc": "#00ff00",
    }
    awtrix3_send_app(
        config["awtrix3"]["url"],
        app,
        data_app,
        config["settings"]["app_scroll_duration"],
        config["settings"]["app_show_time"],
    )
```
Dont forget the 
```        "progress": int(data["pv_Akkustand_SOC"]),```
for the "SOC" Progress Bar
