### ISSUE TITLE
Erster Eindruck

### ISSUE THREAD

**Issue by fnolting** [Deepintheeast/AWTRIX3-Connector#3]
Hallo und vielen Dank für deinen AWTRIX-Connector :) Es wäre toll, wenn man auch den Host und den Port als Variable übergeben könnte (aktuell hardcoded in der funktionen.py) und eventuell auch einen Schalter für SSL einbauen könnte. Ich habe meine ganze Solaranzeige-Installation auf einen anderen Port und SSL umgebaut und kann das jetzt natürlich im Code deines Connectors entsprechend anpassen, aber schöner wäre es natürlich über Variablen in der config.ini :)

--- EDIT ---
Noch was ist mir aufgefallen: Bei mir befindet sich der SOC nicht im Measurement "Batterie" sondern in "Service" und heißt "Akkustand_SOC" und die "Wh_GesamtHeute" im Measurement "Summen" hießen bei mir "SummeWattstundenGesamtHeute". Keine Ahnung woher die Abweichung kommt, eventuell andere Version vom solaranzeige Image..?

--- EDIT 2 ---
Einen hab ich noch: pv.py Line 17: Wenn die Wh_GesamtHeute aus irgendeinem Grund 0 sein sollten, passiert hier eine Division durch Null. Vielleicht könnte man vorher abchecken, ob Wattstunden > 0 sind.

**Comment by Deepintheeast** [comment]
Danke für Dein Feedback!  
Einiges konnten wir ja schon klären, der Rest kommt auf die ToDo Liste!

**Comment by Deepintheeast** [comment]
zu ---Edit2---
die division erfolgt doch durch 1000 um in kWh umzurechnen!
und 0 : 1000 bleibt 0 sollte eigentlich so funktionieren!
