### ISSUE TITLE
Display Not going back to day Mode.

### ISSUE THREAD

**Issue by thedoctor586** [Deepintheeast/AWTRIX3-Connector#4]
Hej,

i‘ve Set astro to 0. so i use timeframe for day/Night Mode. But After Nightmode it‘s Not switching Display to daymode although I Set light to 255 instead of Auto. Any idea?

**Comment by Deepintheeast** [comment]
Hi,
i will check this on the Weekend!

**Comment by Deepintheeast** [comment]
Ok, its a bug!

Please change Line 487 in funktionen.py

from:
```
 awtrix3_url = url = url + "/api/settings"    
```
to
```
 awtrix3_url = url + "/api/settings"
```
I hope this will solve your Problem!

**Comment by thedoctor586** [comment]
Hej, was in vacation. The Display still keeps nightmode and Not changing to daymode

**Comment by Deepintheeast** [comment]
Ok, show me your "config.ini".

**Comment by thedoctor586** [comment]
attached the config content

Am Mo., 24. Juni 2024 u
[config.txt](https://github.com/user-attachments/files/15956119/config.txt)
m 08:51 Uhr schrieb Deepintheeast <
***@***.***>:

**Comment by Deepintheeast** [comment]
Sorry, no attachment?
Use "Copy Paste"!

**Comment by thedoctor586** [comment]
[config.txt](https://github.com/user-attachments/files/15956121/config.txt)

should be added now.

**Comment by Deepintheeast** [comment]
Ok, your config looks fine! Please change your "funktionen.py"
````
cd ~/scripts/AWTRIX3-Connector/
rm funktionen.py 
wget https://raw.githubusercontent.com/Deepintheeast/AWTRIX3-Connector/main/funktionen.py
sudo systemctl restart awtrix3-connector.service 
 ````
 fingers crossed!

**Comment by thedoctor586** [comment]
Hey, thank you for your effort. Seems it‘s Wirkung Fine now. Display switched Fine from Night to day Mode.

**Comment by Deepintheeast** [comment]
Ok, have fun!
